# Local vs Global Rotations
This script computes local (relative) rotations and global rotations of same quantities and shows the resulting frame.

In [1]:
import open3d as o3d
import copy
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
mesh = o3d.geometry.TriangleMesh.create_coordinate_frame()
o3d.visualization.draw_geometries([mesh])

Frames in `open3d` have the $Z$ axis *exiting* the screen.  
We apply the following consecutive rotations to have $X$ axis *exiting* the screen and $Z$ axis pointing up:

1. rotate $-\frac{\pi}{2} \ [rad]$  around $X$ axis

2. rotate $-\frac{\pi}{2} \ [rad]$  around $Z$ axis

In [3]:
Rmx = mesh.get_rotation_matrix_from_xyz((-np.pi / 2., 0, 0))
Rmz = mesh.get_rotation_matrix_from_xyz((0, 0, -np.pi / 2.))

R = Rmx@Rmz
mesh_to_plot = [copy.deepcopy(mesh).rotate(R)]
o3d.visualization.draw_geometries(mesh_to_plot)

We now define the following *single rotations* about main axes of $\frac{\pi}{2} \ [rad]$ $\mathbf{R}_X$, $\mathbf{R}_Y$, and $\mathbf{R}_Z$:

In [4]:
Rx = mesh.get_rotation_matrix_from_xyz((np.pi / 2., 0, 0))
print(f"Rx:\n {Rx}")
Ry = mesh.get_rotation_matrix_from_xyz((0, np.pi / 2., 0))
print(f"Ry:\n {Ry}")
Rz = mesh.get_rotation_matrix_from_xyz((0, 0, np.pi / 2.))
print(f"Rz:\n {Rz}")

Rx:
 [[ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17]]
Ry:
 [[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]
Rz:
 [[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


## Relative Rotations
We apply the rotations consecutively to achieve relative rotations in local axis $\mathbf{R} = \mathbf{R}_X\mathbf{R}_Y\mathbf{R}_Z$:

In [5]:
R1 = R@Rx
m1 = copy.deepcopy(mesh).translate((2, 0, 0))
mesh_to_plot.append(m1.rotate(R1))

R2 = R1@Ry
m2 = copy.deepcopy(mesh).translate((3.3, 0, 0))
mesh_to_plot.append(m2.rotate(R2))

R3 = R2@Rz
m3 = copy.deepcopy(mesh).translate((5.3, 0, 0))
mesh_to_plot.append(m3.rotate(R3))

To get the relative final rotation we need to undo the initial rotation

In [6]:
print(f"Final Relative Rotation Matrx:\n {R.transpose()@R3}")
o3d.visualization.draw_geometries(mesh_to_plot)

Final Relative Rotation Matrx:
 [[ 1.23259516e-32 -6.12323400e-17  1.00000000e+00]
 [ 1.22464680e-16 -1.00000000e+00 -6.12323400e-17]
 [ 1.00000000e+00  1.22464680e-16  0.00000000e+00]]


## Global Rotations
We apply the rotations consecutively to achieve rotations in global axis $\mathbf{R} = \mathbf{R}_Z\mathbf{R}_Y\mathbf{R}_X$:

In [7]:
m0 = copy.deepcopy(mesh).translate((0, -2, 0))
mesh_to_plot.append(m0.rotate(R))

m1 = copy.deepcopy(mesh).translate((2, -2, 0))
mesh_to_plot.append(m1.rotate(R1))
#
R4 = R@Ry@Rx
m4 = copy.deepcopy(mesh).translate((3.3, -2.1, 0))
mesh_to_plot.append(m4.rotate(R4))
#
R5 = R@Rz@Ry@Rx
m5 = copy.deepcopy(mesh).translate((5.3, -2.1, 0))
mesh_to_plot.append(m5.rotate(R5))

To get the global final rotation we need to undo the initial rotation

In [8]:
print(f"Final Global Rotation Matrx:\n {R.transpose()@R5}")
o3d.visualization.draw_geometries(mesh_to_plot)

Final Global Rotation Matrx:
 [[ 0.000000e+00  0.000000e+00  1.000000e+00]
 [ 6.123234e-17  1.000000e+00  0.000000e+00]
 [-1.000000e+00  6.123234e-17  0.000000e+00]]
